#A standalone skript to generate ID with a list.
#Imagine having a list like {mylist} = 1,2,3 <- The code return 4
#    For 1,3,4 <- Return 2
#    For 1,6,7 <- Return 2
#    For 3,4,6 <- Return 1
#    For nothing <- Return 1

function utils_genID(list: numbers) :: number:
    if size of {_list::*} is 0: 
        return 1
    set {_i} to 1
    while {_list::*} contains {_i}:
        add 1 to {_i}
    return {_i}
